version: "3.7"

services:
  database:
    image: mysql:5.7
    enviroment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - clarusnet
  
  bookstore-app:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
    driver: bridge
